/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ControlCalidad {
  'id' : string,
  'foto' : [] | [ExternalBlob],
  'lote' : string,
  'empacadorId' : string,
  'cantidadMuestras' : bigint,
  'horaRegistro' : string,
  'controladorId' : string,
  'dentroRangoPeso' : boolean,
  'defectos' : Array<DefectoCantidad>,
  'fecha' : bigint,
}
export interface ControlCalidadConControlador {
  'control' : ControlCalidad,
  'controlador' : Controlador,
}
export interface Controlador {
  'id' : string,
  'activo' : boolean,
  'nombre' : string,
}
export type Defecto = { 'podredumbre' : null } |
  { 'cracking' : null } |
  { 'raset' : null } |
  { 'golpeSol' : null };
export interface DefectoCantidad { 'defecto' : Defecto, 'cantidad' : bigint }
export interface Empacador {
  'id' : string,
  'activo' : boolean,
  'color' : string,
  'identificador' : string,
}
export type ExternalBlob = Uint8Array;
export interface Filtro {
  'empacadorId' : [] | [string],
  'fechaInicio' : [] | [bigint],
  'defecto' : [] | [Defecto],
  'fechaFin' : [] | [bigint],
  'controladorId' : [] | [string],
  'dentroRangoPeso' : [] | [boolean],
}
export interface MuestraPlanilla {
  'id' : string,
  'controlador' : Controlador,
  'foto' : [] | [ExternalBlob],
  'lote' : string,
  'cantidadMuestras' : bigint,
  'empacador' : Empacador,
  'horaRegistro' : string,
  'dentroRangoPeso' : boolean,
  'defectos' : Array<DefectoCantidad>,
  'fecha' : bigint,
}
export interface ReporteDiarioConControlador {
  'totalDefectosPorTipo' : Array<[Defecto, bigint]>,
  'porcentajeFueraRangoPeso' : number,
  'porcentajeDentroRangoPeso' : number,
  'porcentajeDefectos' : number,
  'totalFrutasAfectadas' : bigint,
  'totalFrutasSinDefectos' : bigint,
  'totalMuestras' : bigint,
  'controles' : Array<ControlCalidadConControlador>,
  'totalFueraRangoPeso' : bigint,
  'totalDentroRangoPeso' : bigint,
  'porcentajeSinDefectos' : number,
  'fecha' : bigint,
}
export interface ReporteRangoConControlador {
  'totalDefectosPorTipo' : Array<[Defecto, bigint]>,
  'porcentajeFueraRangoPeso' : number,
  'porcentajeDentroRangoPeso' : number,
  'porcentajeDefectos' : number,
  'totalFrutasAfectadas' : bigint,
  'totalFrutasSinDefectos' : bigint,
  'totalMuestras' : bigint,
  'controles' : Array<ControlCalidadConControlador>,
  'fechaInicio' : bigint,
  'totalFueraRangoPeso' : bigint,
  'totalDentroRangoPeso' : bigint,
  'fechaFin' : bigint,
  'porcentajeSinDefectos' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : [] | [UserProfile],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'agregarControlador' : ActorMethod<[string], string>,
  'agregarEmpacador' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'eliminarControl' : ActorMethod<[string], string>,
  'eliminarControlador' : ActorMethod<[string], string>,
  'eliminarEmpacador' : ActorMethod<[string], string>,
  'getAllUserRoles' : ActorMethod<[], Array<UserWithRole>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'modificarControlador' : ActorMethod<[string, string], string>,
  'modificarEmpacador' : ActorMethod<[string, string, string], string>,
  'obtenerControl' : ActorMethod<[string], [] | [ControlCalidad]>,
  'obtenerControladoresActivos' : ActorMethod<[], Array<Controlador>>,
  'obtenerControlesFiltrados' : ActorMethod<
    [Filtro],
    Array<ControlCalidadConControlador>
  >,
  'obtenerDetalleMuestra' : ActorMethod<[string], [] | [MuestraPlanilla]>,
  'obtenerEmpacadoresActivos' : ActorMethod<[], Array<Empacador>>,
  'obtenerHistorial' : ActorMethod<[], Array<ControlCalidadConControlador>>,
  'obtenerIdentificadoresParaConvertir' : ActorMethod<
    [],
    Array<[string, boolean]>
  >,
  'obtenerMuestrasParaPlanilla' : ActorMethod<
    [bigint, bigint],
    Array<MuestraPlanilla>
  >,
  'obtenerProximoIdentificador' : ActorMethod<[], string>,
  'obtenerReporteDiario' : ActorMethod<
    [bigint],
    [] | [ReporteDiarioConControlador]
  >,
  'obtenerReporteRango' : ActorMethod<
    [bigint, bigint],
    [] | [ReporteRangoConControlador]
  >,
  'obtenerReportesPorRango' : ActorMethod<
    [bigint, bigint],
    Array<ReporteDiarioConControlador>
  >,
  'registrarControl' : ActorMethod<
    [
      Array<DefectoCantidad>,
      [] | [ExternalBlob],
      bigint,
      string,
      string,
      boolean,
    ],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];