/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserWithRole = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Defecto = IDL.Variant({
  'podredumbre' : IDL.Null,
  'cracking' : IDL.Null,
  'raset' : IDL.Null,
  'golpeSol' : IDL.Null,
});
export const DefectoCantidad = IDL.Record({
  'defecto' : Defecto,
  'cantidad' : IDL.Nat,
});
export const ControlCalidad = IDL.Record({
  'id' : IDL.Text,
  'foto' : IDL.Opt(ExternalBlob),
  'lote' : IDL.Text,
  'empacadorId' : IDL.Text,
  'cantidadMuestras' : IDL.Nat,
  'horaRegistro' : IDL.Text,
  'controladorId' : IDL.Text,
  'dentroRangoPeso' : IDL.Bool,
  'defectos' : IDL.Vec(DefectoCantidad),
  'fecha' : IDL.Int,
});
export const Controlador = IDL.Record({
  'id' : IDL.Text,
  'activo' : IDL.Bool,
  'nombre' : IDL.Text,
});
export const Filtro = IDL.Record({
  'empacadorId' : IDL.Opt(IDL.Text),
  'fechaInicio' : IDL.Opt(IDL.Int),
  'defecto' : IDL.Opt(Defecto),
  'fechaFin' : IDL.Opt(IDL.Int),
  'controladorId' : IDL.Opt(IDL.Text),
  'dentroRangoPeso' : IDL.Opt(IDL.Bool),
});
export const ControlCalidadConControlador = IDL.Record({
  'control' : ControlCalidad,
  'controlador' : Controlador,
});
export const Empacador = IDL.Record({
  'id' : IDL.Text,
  'activo' : IDL.Bool,
  'color' : IDL.Text,
  'identificador' : IDL.Text,
});
export const MuestraPlanilla = IDL.Record({
  'id' : IDL.Text,
  'controlador' : Controlador,
  'foto' : IDL.Opt(ExternalBlob),
  'lote' : IDL.Text,
  'cantidadMuestras' : IDL.Nat,
  'empacador' : Empacador,
  'horaRegistro' : IDL.Text,
  'dentroRangoPeso' : IDL.Bool,
  'defectos' : IDL.Vec(DefectoCantidad),
  'fecha' : IDL.Int,
});
export const ReporteDiarioConControlador = IDL.Record({
  'totalDefectosPorTipo' : IDL.Vec(IDL.Tuple(Defecto, IDL.Nat)),
  'porcentajeFueraRangoPeso' : IDL.Float64,
  'porcentajeDentroRangoPeso' : IDL.Float64,
  'porcentajeDefectos' : IDL.Float64,
  'totalFrutasAfectadas' : IDL.Nat,
  'totalFrutasSinDefectos' : IDL.Nat,
  'totalMuestras' : IDL.Nat,
  'controles' : IDL.Vec(ControlCalidadConControlador),
  'totalFueraRangoPeso' : IDL.Nat,
  'totalDentroRangoPeso' : IDL.Nat,
  'porcentajeSinDefectos' : IDL.Float64,
  'fecha' : IDL.Int,
});
export const ReporteRangoConControlador = IDL.Record({
  'totalDefectosPorTipo' : IDL.Vec(IDL.Tuple(Defecto, IDL.Nat)),
  'porcentajeFueraRangoPeso' : IDL.Float64,
  'porcentajeDentroRangoPeso' : IDL.Float64,
  'porcentajeDefectos' : IDL.Float64,
  'totalFrutasAfectadas' : IDL.Nat,
  'totalFrutasSinDefectos' : IDL.Nat,
  'totalMuestras' : IDL.Nat,
  'controles' : IDL.Vec(ControlCalidadConControlador),
  'fechaInicio' : IDL.Int,
  'totalFueraRangoPeso' : IDL.Nat,
  'totalDentroRangoPeso' : IDL.Nat,
  'fechaFin' : IDL.Int,
  'porcentajeSinDefectos' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'agregarControlador' : IDL.Func([IDL.Text], [IDL.Text], []),
  'agregarEmpacador' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'eliminarControl' : IDL.Func([IDL.Text], [IDL.Text], []),
  'eliminarControlador' : IDL.Func([IDL.Text], [IDL.Text], []),
  'eliminarEmpacador' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllUserRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'modificarControlador' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'modificarEmpacador' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'obtenerControl' : IDL.Func([IDL.Text], [IDL.Opt(ControlCalidad)], ['query']),
  'obtenerControladoresActivos' : IDL.Func(
      [],
      [IDL.Vec(Controlador)],
      ['query'],
    ),
  'obtenerControlesFiltrados' : IDL.Func(
      [Filtro],
      [IDL.Vec(ControlCalidadConControlador)],
      ['query'],
    ),
  'obtenerDetalleMuestra' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MuestraPlanilla)],
      ['query'],
    ),
  'obtenerEmpacadoresActivos' : IDL.Func([], [IDL.Vec(Empacador)], ['query']),
  'obtenerHistorial' : IDL.Func(
      [],
      [IDL.Vec(ControlCalidadConControlador)],
      ['query'],
    ),
  'obtenerIdentificadoresParaConvertir' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'obtenerMuestrasParaPlanilla' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(MuestraPlanilla)],
      ['query'],
    ),
  'obtenerProximoIdentificador' : IDL.Func([], [IDL.Text], ['query']),
  'obtenerReporteDiario' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(ReporteDiarioConControlador)],
      ['query'],
    ),
  'obtenerReporteRango' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Opt(ReporteRangoConControlador)],
      ['query'],
    ),
  'obtenerReportesPorRango' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(ReporteDiarioConControlador)],
      ['query'],
    ),
  'registrarControl' : IDL.Func(
      [
        IDL.Vec(DefectoCantidad),
        IDL.Opt(ExternalBlob),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserWithRole = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Defecto = IDL.Variant({
    'podredumbre' : IDL.Null,
    'cracking' : IDL.Null,
    'raset' : IDL.Null,
    'golpeSol' : IDL.Null,
  });
  const DefectoCantidad = IDL.Record({
    'defecto' : Defecto,
    'cantidad' : IDL.Nat,
  });
  const ControlCalidad = IDL.Record({
    'id' : IDL.Text,
    'foto' : IDL.Opt(ExternalBlob),
    'lote' : IDL.Text,
    'empacadorId' : IDL.Text,
    'cantidadMuestras' : IDL.Nat,
    'horaRegistro' : IDL.Text,
    'controladorId' : IDL.Text,
    'dentroRangoPeso' : IDL.Bool,
    'defectos' : IDL.Vec(DefectoCantidad),
    'fecha' : IDL.Int,
  });
  const Controlador = IDL.Record({
    'id' : IDL.Text,
    'activo' : IDL.Bool,
    'nombre' : IDL.Text,
  });
  const Filtro = IDL.Record({
    'empacadorId' : IDL.Opt(IDL.Text),
    'fechaInicio' : IDL.Opt(IDL.Int),
    'defecto' : IDL.Opt(Defecto),
    'fechaFin' : IDL.Opt(IDL.Int),
    'controladorId' : IDL.Opt(IDL.Text),
    'dentroRangoPeso' : IDL.Opt(IDL.Bool),
  });
  const ControlCalidadConControlador = IDL.Record({
    'control' : ControlCalidad,
    'controlador' : Controlador,
  });
  const Empacador = IDL.Record({
    'id' : IDL.Text,
    'activo' : IDL.Bool,
    'color' : IDL.Text,
    'identificador' : IDL.Text,
  });
  const MuestraPlanilla = IDL.Record({
    'id' : IDL.Text,
    'controlador' : Controlador,
    'foto' : IDL.Opt(ExternalBlob),
    'lote' : IDL.Text,
    'cantidadMuestras' : IDL.Nat,
    'empacador' : Empacador,
    'horaRegistro' : IDL.Text,
    'dentroRangoPeso' : IDL.Bool,
    'defectos' : IDL.Vec(DefectoCantidad),
    'fecha' : IDL.Int,
  });
  const ReporteDiarioConControlador = IDL.Record({
    'totalDefectosPorTipo' : IDL.Vec(IDL.Tuple(Defecto, IDL.Nat)),
    'porcentajeFueraRangoPeso' : IDL.Float64,
    'porcentajeDentroRangoPeso' : IDL.Float64,
    'porcentajeDefectos' : IDL.Float64,
    'totalFrutasAfectadas' : IDL.Nat,
    'totalFrutasSinDefectos' : IDL.Nat,
    'totalMuestras' : IDL.Nat,
    'controles' : IDL.Vec(ControlCalidadConControlador),
    'totalFueraRangoPeso' : IDL.Nat,
    'totalDentroRangoPeso' : IDL.Nat,
    'porcentajeSinDefectos' : IDL.Float64,
    'fecha' : IDL.Int,
  });
  const ReporteRangoConControlador = IDL.Record({
    'totalDefectosPorTipo' : IDL.Vec(IDL.Tuple(Defecto, IDL.Nat)),
    'porcentajeFueraRangoPeso' : IDL.Float64,
    'porcentajeDentroRangoPeso' : IDL.Float64,
    'porcentajeDefectos' : IDL.Float64,
    'totalFrutasAfectadas' : IDL.Nat,
    'totalFrutasSinDefectos' : IDL.Nat,
    'totalMuestras' : IDL.Nat,
    'controles' : IDL.Vec(ControlCalidadConControlador),
    'fechaInicio' : IDL.Int,
    'totalFueraRangoPeso' : IDL.Nat,
    'totalDentroRangoPeso' : IDL.Nat,
    'fechaFin' : IDL.Int,
    'porcentajeSinDefectos' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'agregarControlador' : IDL.Func([IDL.Text], [IDL.Text], []),
    'agregarEmpacador' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'eliminarControl' : IDL.Func([IDL.Text], [IDL.Text], []),
    'eliminarControlador' : IDL.Func([IDL.Text], [IDL.Text], []),
    'eliminarEmpacador' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllUserRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'modificarControlador' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'modificarEmpacador' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'obtenerControl' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ControlCalidad)],
        ['query'],
      ),
    'obtenerControladoresActivos' : IDL.Func(
        [],
        [IDL.Vec(Controlador)],
        ['query'],
      ),
    'obtenerControlesFiltrados' : IDL.Func(
        [Filtro],
        [IDL.Vec(ControlCalidadConControlador)],
        ['query'],
      ),
    'obtenerDetalleMuestra' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MuestraPlanilla)],
        ['query'],
      ),
    'obtenerEmpacadoresActivos' : IDL.Func([], [IDL.Vec(Empacador)], ['query']),
    'obtenerHistorial' : IDL.Func(
        [],
        [IDL.Vec(ControlCalidadConControlador)],
        ['query'],
      ),
    'obtenerIdentificadoresParaConvertir' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'obtenerMuestrasParaPlanilla' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(MuestraPlanilla)],
        ['query'],
      ),
    'obtenerProximoIdentificador' : IDL.Func([], [IDL.Text], ['query']),
    'obtenerReporteDiario' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(ReporteDiarioConControlador)],
        ['query'],
      ),
    'obtenerReporteRango' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Opt(ReporteRangoConControlador)],
        ['query'],
      ),
    'obtenerReportesPorRango' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(ReporteDiarioConControlador)],
        ['query'],
      ),
    'registrarControl' : IDL.Func(
        [
          IDL.Vec(DefectoCantidad),
          IDL.Opt(ExternalBlob),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };