/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Filtro {
    empacadorId?: string;
    fechaInicio?: bigint;
    defecto?: Defecto;
    fechaFin?: bigint;
    controladorId?: string;
    dentroRangoPeso?: boolean;
}
export interface ControlCalidadConControlador {
    control: ControlCalidad;
    controlador: Controlador;
}
export interface Empacador {
    id: string;
    activo: boolean;
    color: string;
    identificador: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DefectoCantidad {
    defecto: Defecto;
    cantidad: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ReporteDiarioConControlador {
    totalDefectosPorTipo: Array<[Defecto, bigint]>;
    porcentajeFueraRangoPeso: number;
    porcentajeDentroRangoPeso: number;
    porcentajeDefectos: number;
    totalFrutasAfectadas: bigint;
    totalFrutasSinDefectos: bigint;
    totalMuestras: bigint;
    controles: Array<ControlCalidadConControlador>;
    totalFueraRangoPeso: bigint;
    totalDentroRangoPeso: bigint;
    porcentajeSinDefectos: number;
    fecha: bigint;
}
export interface Controlador {
    id: string;
    activo: boolean;
    nombre: string;
}
export interface ControlCalidad {
    id: string;
    foto?: ExternalBlob;
    lote: string;
    empacadorId: string;
    cantidadMuestras: bigint;
    horaRegistro: string;
    controladorId: string;
    dentroRangoPeso: boolean;
    defectos: Array<DefectoCantidad>;
    fecha: bigint;
}
export interface MuestraPlanilla {
    id: string;
    controlador: Controlador;
    foto?: ExternalBlob;
    lote: string;
    cantidadMuestras: bigint;
    empacador: Empacador;
    horaRegistro: string;
    dentroRangoPeso: boolean;
    defectos: Array<DefectoCantidad>;
    fecha: bigint;
}
export interface ReporteRangoConControlador {
    totalDefectosPorTipo: Array<[Defecto, bigint]>;
    porcentajeFueraRangoPeso: number;
    porcentajeDentroRangoPeso: number;
    porcentajeDefectos: number;
    totalFrutasAfectadas: bigint;
    totalFrutasSinDefectos: bigint;
    totalMuestras: bigint;
    controles: Array<ControlCalidadConControlador>;
    fechaInicio: bigint;
    totalFueraRangoPeso: bigint;
    totalDentroRangoPeso: bigint;
    fechaFin: bigint;
    porcentajeSinDefectos: number;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Defecto {
    podredumbre = "podredumbre",
    cracking = "cracking",
    raset = "raset",
    golpeSol = "golpeSol"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    agregarControlador(nombre: string): Promise<string>;
    agregarEmpacador(identificador: string, color: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    eliminarControl(id: string): Promise<string>;
    eliminarControlador(id: string): Promise<string>;
    eliminarEmpacador(id: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    modificarControlador(id: string, nuevoNombre: string): Promise<string>;
    modificarEmpacador(id: string, nuevoIdentificador: string, nuevoColor: string): Promise<string>;
    obtenerControl(id: string): Promise<ControlCalidad | null>;
    obtenerControladoresActivos(): Promise<Array<Controlador>>;
    obtenerControlesFiltrados(filtro: Filtro): Promise<Array<ControlCalidadConControlador>>;
    obtenerDetalleMuestra(id: string): Promise<MuestraPlanilla | null>;
    obtenerEmpacadoresActivos(): Promise<Array<Empacador>>;
    obtenerHistorial(): Promise<Array<ControlCalidadConControlador>>;
    obtenerIdentificadoresParaConvertir(): Promise<Array<[string, boolean]>>;
    obtenerMuestrasParaPlanilla(fechaInicio: bigint, fechaFin: bigint): Promise<Array<MuestraPlanilla>>;
    obtenerProximoIdentificador(): Promise<string>;
    obtenerReporteDiario(fecha: bigint): Promise<ReporteDiarioConControlador | null>;
    obtenerReporteRango(fechaInicio: bigint, fechaFin: bigint): Promise<ReporteRangoConControlador | null>;
    obtenerReportesPorRango(fechaInicio: bigint, fechaFin: bigint): Promise<Array<ReporteDiarioConControlador>>;
    registrarControl(defectos: Array<DefectoCantidad>, foto: ExternalBlob | null, cantidadMuestras: bigint, empacadorId: string, controladorId: string, dentroRangoPeso: boolean): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { ControlCalidad as _ControlCalidad, ControlCalidadConControlador as _ControlCalidadConControlador, Controlador as _Controlador, Defecto as _Defecto, DefectoCantidad as _DefectoCantidad, Empacador as _Empacador, ExternalBlob as _ExternalBlob, Filtro as _Filtro, MuestraPlanilla as _MuestraPlanilla, ReporteDiarioConControlador as _ReporteDiarioConControlador, ReporteRangoConControlador as _ReporteRangoConControlador, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async agregarControlador(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.agregarControlador(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.agregarControlador(arg0);
            return result;
        }
    }
    async agregarEmpacador(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.agregarEmpacador(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.agregarEmpacador(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async eliminarControl(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.eliminarControl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.eliminarControl(arg0);
            return result;
        }
    }
    async eliminarControlador(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.eliminarControlador(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.eliminarControlador(arg0);
            return result;
        }
    }
    async eliminarEmpacador(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.eliminarEmpacador(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.eliminarEmpacador(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async modificarControlador(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.modificarControlador(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modificarControlador(arg0, arg1);
            return result;
        }
    }
    async modificarEmpacador(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.modificarEmpacador(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modificarEmpacador(arg0, arg1, arg2);
            return result;
        }
    }
    async obtenerControl(arg0: string): Promise<ControlCalidad | null> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerControl(arg0);
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerControl(arg0);
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async obtenerControladoresActivos(): Promise<Array<Controlador>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerControladoresActivos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerControladoresActivos();
            return result;
        }
    }
    async obtenerControlesFiltrados(arg0: Filtro): Promise<Array<ControlCalidadConControlador>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerControlesFiltrados(to_candid_Filtro_n23(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerControlesFiltrados(to_candid_Filtro_n23(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async obtenerDetalleMuestra(arg0: string): Promise<MuestraPlanilla | null> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerDetalleMuestra(arg0);
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerDetalleMuestra(arg0);
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async obtenerEmpacadoresActivos(): Promise<Array<Empacador>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerEmpacadoresActivos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerEmpacadoresActivos();
            return result;
        }
    }
    async obtenerHistorial(): Promise<Array<ControlCalidadConControlador>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerHistorial();
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerHistorial();
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async obtenerIdentificadoresParaConvertir(): Promise<Array<[string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerIdentificadoresParaConvertir();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerIdentificadoresParaConvertir();
            return result;
        }
    }
    async obtenerMuestrasParaPlanilla(arg0: bigint, arg1: bigint): Promise<Array<MuestraPlanilla>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerMuestrasParaPlanilla(arg0, arg1);
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerMuestrasParaPlanilla(arg0, arg1);
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async obtenerProximoIdentificador(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerProximoIdentificador();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerProximoIdentificador();
            return result;
        }
    }
    async obtenerReporteDiario(arg0: bigint): Promise<ReporteDiarioConControlador | null> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerReporteDiario(arg0);
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerReporteDiario(arg0);
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async obtenerReporteRango(arg0: bigint, arg1: bigint): Promise<ReporteRangoConControlador | null> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerReporteRango(arg0, arg1);
                return from_candid_opt_n39(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerReporteRango(arg0, arg1);
            return from_candid_opt_n39(this.uploadFile, this.downloadFile, result);
        }
    }
    async obtenerReportesPorRango(arg0: bigint, arg1: bigint): Promise<Array<ReporteDiarioConControlador>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenerReportesPorRango(arg0, arg1);
                return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenerReportesPorRango(arg0, arg1);
            return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async registrarControl(arg0: Array<DefectoCantidad>, arg1: ExternalBlob | null, arg2: bigint, arg3: string, arg4: string, arg5: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registrarControl(to_candid_vec_n43(this.uploadFile, this.downloadFile, arg0), await to_candid_opt_n46(this.uploadFile, this.downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registrarControl(to_candid_vec_n43(this.uploadFile, this.downloadFile, arg0), await to_candid_opt_n46(this.uploadFile, this.downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
async function from_candid_ControlCalidadConControlador_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ControlCalidadConControlador): Promise<ControlCalidadConControlador> {
    return await from_candid_record_n29(uploadFile, downloadFile, value);
}
async function from_candid_ControlCalidad_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ControlCalidad): Promise<ControlCalidad> {
    return await from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_DefectoCantidad_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DefectoCantidad): DefectoCantidad {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_Defecto_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Defecto): Defecto {
    return from_candid_variant_n22(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_MuestraPlanilla_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuestraPlanilla): Promise<MuestraPlanilla> {
    return await from_candid_record_n32(uploadFile, downloadFile, value);
}
async function from_candid_ReporteDiarioConControlador_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReporteDiarioConControlador): Promise<ReporteDiarioConControlador> {
    return await from_candid_record_n36(uploadFile, downloadFile, value);
}
async function from_candid_ReporteRangoConControlador_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReporteRangoConControlador): Promise<ReporteRangoConControlador> {
    return await from_candid_record_n41(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ControlCalidad]): Promise<ControlCalidad | null> {
    return value.length === 0 ? null : await from_candid_ControlCalidad_n14(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MuestraPlanilla]): Promise<MuestraPlanilla | null> {
    return value.length === 0 ? null : await from_candid_MuestraPlanilla_n31(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReporteDiarioConControlador]): Promise<ReporteDiarioConControlador | null> {
    return value.length === 0 ? null : await from_candid_ReporteDiarioConControlador_n35(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReporteRangoConControlador]): Promise<ReporteRangoConControlador | null> {
    return value.length === 0 ? null : await from_candid_ReporteRangoConControlador_n40(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    foto: [] | [_ExternalBlob];
    lote: string;
    empacadorId: string;
    cantidadMuestras: bigint;
    horaRegistro: string;
    controladorId: string;
    dentroRangoPeso: boolean;
    defectos: Array<_DefectoCantidad>;
    fecha: bigint;
}): Promise<{
    id: string;
    foto?: ExternalBlob;
    lote: string;
    empacadorId: string;
    cantidadMuestras: bigint;
    horaRegistro: string;
    controladorId: string;
    dentroRangoPeso: boolean;
    defectos: Array<DefectoCantidad>;
    fecha: bigint;
}> {
    return {
        id: value.id,
        foto: record_opt_to_undefined(await from_candid_opt_n16(uploadFile, downloadFile, value.foto)),
        lote: value.lote,
        empacadorId: value.empacadorId,
        cantidadMuestras: value.cantidadMuestras,
        horaRegistro: value.horaRegistro,
        controladorId: value.controladorId,
        dentroRangoPeso: value.dentroRangoPeso,
        defectos: from_candid_vec_n18(uploadFile, downloadFile, value.defectos),
        fecha: value.fecha
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    defecto: _Defecto;
    cantidad: bigint;
}): {
    defecto: Defecto;
    cantidad: bigint;
} {
    return {
        defecto: from_candid_Defecto_n21(uploadFile, downloadFile, value.defecto),
        cantidad: value.cantidad
    };
}
async function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    control: _ControlCalidad;
    controlador: _Controlador;
}): Promise<{
    control: ControlCalidad;
    controlador: Controlador;
}> {
    return {
        control: await from_candid_ControlCalidad_n14(uploadFile, downloadFile, value.control),
        controlador: value.controlador
    };
}
async function from_candid_record_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    controlador: _Controlador;
    foto: [] | [_ExternalBlob];
    lote: string;
    cantidadMuestras: bigint;
    empacador: _Empacador;
    horaRegistro: string;
    dentroRangoPeso: boolean;
    defectos: Array<_DefectoCantidad>;
    fecha: bigint;
}): Promise<{
    id: string;
    controlador: Controlador;
    foto?: ExternalBlob;
    lote: string;
    cantidadMuestras: bigint;
    empacador: Empacador;
    horaRegistro: string;
    dentroRangoPeso: boolean;
    defectos: Array<DefectoCantidad>;
    fecha: bigint;
}> {
    return {
        id: value.id,
        controlador: value.controlador,
        foto: record_opt_to_undefined(await from_candid_opt_n16(uploadFile, downloadFile, value.foto)),
        lote: value.lote,
        cantidadMuestras: value.cantidadMuestras,
        empacador: value.empacador,
        horaRegistro: value.horaRegistro,
        dentroRangoPeso: value.dentroRangoPeso,
        defectos: from_candid_vec_n18(uploadFile, downloadFile, value.defectos),
        fecha: value.fecha
    };
}
async function from_candid_record_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalDefectosPorTipo: Array<[_Defecto, bigint]>;
    porcentajeFueraRangoPeso: number;
    porcentajeDentroRangoPeso: number;
    porcentajeDefectos: number;
    totalFrutasAfectadas: bigint;
    totalFrutasSinDefectos: bigint;
    totalMuestras: bigint;
    controles: Array<_ControlCalidadConControlador>;
    totalFueraRangoPeso: bigint;
    totalDentroRangoPeso: bigint;
    porcentajeSinDefectos: number;
    fecha: bigint;
}): Promise<{
    totalDefectosPorTipo: Array<[Defecto, bigint]>;
    porcentajeFueraRangoPeso: number;
    porcentajeDentroRangoPeso: number;
    porcentajeDefectos: number;
    totalFrutasAfectadas: bigint;
    totalFrutasSinDefectos: bigint;
    totalMuestras: bigint;
    controles: Array<ControlCalidadConControlador>;
    totalFueraRangoPeso: bigint;
    totalDentroRangoPeso: bigint;
    porcentajeSinDefectos: number;
    fecha: bigint;
}> {
    return {
        totalDefectosPorTipo: from_candid_vec_n37(uploadFile, downloadFile, value.totalDefectosPorTipo),
        porcentajeFueraRangoPeso: value.porcentajeFueraRangoPeso,
        porcentajeDentroRangoPeso: value.porcentajeDentroRangoPeso,
        porcentajeDefectos: value.porcentajeDefectos,
        totalFrutasAfectadas: value.totalFrutasAfectadas,
        totalFrutasSinDefectos: value.totalFrutasSinDefectos,
        totalMuestras: value.totalMuestras,
        controles: await from_candid_vec_n27(uploadFile, downloadFile, value.controles),
        totalFueraRangoPeso: value.totalFueraRangoPeso,
        totalDentroRangoPeso: value.totalDentroRangoPeso,
        porcentajeSinDefectos: value.porcentajeSinDefectos,
        fecha: value.fecha
    };
}
async function from_candid_record_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalDefectosPorTipo: Array<[_Defecto, bigint]>;
    porcentajeFueraRangoPeso: number;
    porcentajeDentroRangoPeso: number;
    porcentajeDefectos: number;
    totalFrutasAfectadas: bigint;
    totalFrutasSinDefectos: bigint;
    totalMuestras: bigint;
    controles: Array<_ControlCalidadConControlador>;
    fechaInicio: bigint;
    totalFueraRangoPeso: bigint;
    totalDentroRangoPeso: bigint;
    fechaFin: bigint;
    porcentajeSinDefectos: number;
}): Promise<{
    totalDefectosPorTipo: Array<[Defecto, bigint]>;
    porcentajeFueraRangoPeso: number;
    porcentajeDentroRangoPeso: number;
    porcentajeDefectos: number;
    totalFrutasAfectadas: bigint;
    totalFrutasSinDefectos: bigint;
    totalMuestras: bigint;
    controles: Array<ControlCalidadConControlador>;
    fechaInicio: bigint;
    totalFueraRangoPeso: bigint;
    totalDentroRangoPeso: bigint;
    fechaFin: bigint;
    porcentajeSinDefectos: number;
}> {
    return {
        totalDefectosPorTipo: from_candid_vec_n37(uploadFile, downloadFile, value.totalDefectosPorTipo),
        porcentajeFueraRangoPeso: value.porcentajeFueraRangoPeso,
        porcentajeDentroRangoPeso: value.porcentajeDentroRangoPeso,
        porcentajeDefectos: value.porcentajeDefectos,
        totalFrutasAfectadas: value.totalFrutasAfectadas,
        totalFrutasSinDefectos: value.totalFrutasSinDefectos,
        totalMuestras: value.totalMuestras,
        controles: await from_candid_vec_n27(uploadFile, downloadFile, value.controles),
        fechaInicio: value.fechaInicio,
        totalFueraRangoPeso: value.totalFueraRangoPeso,
        totalDentroRangoPeso: value.totalDentroRangoPeso,
        fechaFin: value.fechaFin,
        porcentajeSinDefectos: value.porcentajeSinDefectos
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Defecto, bigint]): [Defecto, bigint] {
    return [
        from_candid_Defecto_n21(uploadFile, downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    podredumbre: null;
} | {
    cracking: null;
} | {
    raset: null;
} | {
    golpeSol: null;
}): Defecto {
    return "podredumbre" in value ? Defecto.podredumbre : "cracking" in value ? Defecto.cracking : "raset" in value ? Defecto.raset : "golpeSol" in value ? Defecto.golpeSol : value;
}
function from_candid_vec_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DefectoCantidad>): Array<DefectoCantidad> {
    return value.map((x)=>from_candid_DefectoCantidad_n19(uploadFile, downloadFile, x));
}
async function from_candid_vec_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ControlCalidadConControlador>): Promise<Array<ControlCalidadConControlador>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ControlCalidadConControlador_n28(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MuestraPlanilla>): Promise<Array<MuestraPlanilla>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MuestraPlanilla_n31(uploadFile, downloadFile, x)));
}
function from_candid_vec_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Defecto, bigint]>): Array<[Defecto, bigint]> {
    return value.map((x)=>from_candid_tuple_n38(uploadFile, downloadFile, x));
}
async function from_candid_vec_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReporteDiarioConControlador>): Promise<Array<ReporteDiarioConControlador>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ReporteDiarioConControlador_n35(uploadFile, downloadFile, x)));
}
function to_candid_DefectoCantidad_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DefectoCantidad): _DefectoCantidad {
    return to_candid_record_n45(uploadFile, downloadFile, value);
}
function to_candid_Defecto_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Defecto): _Defecto {
    return to_candid_variant_n26(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_Filtro_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Filtro): _Filtro {
    return to_candid_record_n24(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
async function to_candid_opt_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n47(uploadFile, downloadFile, value));
}
function to_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    empacadorId?: string;
    fechaInicio?: bigint;
    defecto?: Defecto;
    fechaFin?: bigint;
    controladorId?: string;
    dentroRangoPeso?: boolean;
}): {
    empacadorId: [] | [string];
    fechaInicio: [] | [bigint];
    defecto: [] | [_Defecto];
    fechaFin: [] | [bigint];
    controladorId: [] | [string];
    dentroRangoPeso: [] | [boolean];
} {
    return {
        empacadorId: value.empacadorId ? candid_some(value.empacadorId) : candid_none(),
        fechaInicio: value.fechaInicio ? candid_some(value.fechaInicio) : candid_none(),
        defecto: value.defecto ? candid_some(to_candid_Defecto_n25(uploadFile, downloadFile, value.defecto)) : candid_none(),
        fechaFin: value.fechaFin ? candid_some(value.fechaFin) : candid_none(),
        controladorId: value.controladorId ? candid_some(value.controladorId) : candid_none(),
        dentroRangoPeso: value.dentroRangoPeso ? candid_some(value.dentroRangoPeso) : candid_none()
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    defecto: Defecto;
    cantidad: bigint;
}): {
    defecto: _Defecto;
    cantidad: bigint;
} {
    return {
        defecto: to_candid_Defecto_n25(uploadFile, downloadFile, value.defecto),
        cantidad: value.cantidad
    };
}
function to_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Defecto): {
    podredumbre: null;
} | {
    cracking: null;
} | {
    raset: null;
} | {
    golpeSol: null;
} {
    return value == Defecto.podredumbre ? {
        podredumbre: null
    } : value == Defecto.cracking ? {
        cracking: null
    } : value == Defecto.raset ? {
        raset: null
    } : value == Defecto.golpeSol ? {
        golpeSol: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DefectoCantidad>): Array<_DefectoCantidad> {
    return value.map((x)=>to_candid_DefectoCantidad_n44(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
